### ISSUE TITLE
Why is this repo not part of dotnet/aspnetcore?

### ISSUE THREAD

**Issue by dagood** [dotnet/cssparser#2]
The package this repo produces is depended on by dotnet/aspnetcore, starting with https://github.com/dotnet/aspnetcore/pull/23657. Why isn't this code checked into dotnet/aspnetcore?

**Comment by SteveSandersonMS** [comment]
The code comes from the WTE team and its ongoing ownership remains split between WTE and aspnetcore. Additionally in aspnetcore we prefer to keep it as an external dependency to avoid any possibility that, if in the future we want to replace it entirely with a different dependency, we don't have cases where others have relied on it being part of aspnetcore.
