### ISSUE TITLE
Plan to use the Arcade SDK toolset?

### ISSUE THREAD

**Issue by dagood** [dotnet/cssparser#3]
Most repos that are distributed in the .NET SDK use the Arcade SDK toolset, https://github.com/dotnet/arcade. This lets the repo take part in trackable dependency flow infrastructure (rather than a hard-coded version number in dotnet/aspnetcore), and provides build infrastructure. It removes the mystery from how a commit from this repo ends up in a package that ends up used by dotnet/aspnetcore.

Is there a plan to use the Arcade SDK to build this repo?

(We encountered this repo while trying to build .NET 5.0 from source for https://github.com/dotnet/source-build. There are plans in the future that will make source-build work more smoothly if each repo uses Arcade infrastructure. I'm wondering what we can expect in the future with this repo.)

**Comment by dagood** [comment]
@SteveSandersonMS, can you help with this question?

I also asked a more general question about why this repo isn't part of dotnet/aspnetcore at https://github.com/dotnet/cssparser/issues/2, if you don't mind.

/cc @JunTaoLuo (do you have context on this repo? We're poking at it from a source-build perspective because of the dependency from dotnet/aspnetcore and lack of documentation in this repo itself.)

**Comment by SteveSandersonMS** [comment]
We don't have any specific plans to change anything about this repo. It's code provided by the WTE team that aspnetcore consumes to handle one internal implementation detail.

Are you saying it will become essential to switch this particular repo to use Arcade at some point? If so, do you know when? If that is the case, we should discuss how that will happen. For example, whether some part of the .NET infrastructure team can help out with that, or whether the ASP.NET Core team needs to budget some time for it in the future.

cc @mkArtakMSFT

**Comment by dagood** [comment]
> Are you saying it will become essential to switch this particular repo to use Arcade at some point?

No, there's no requirement from source-build or from the Arcade team itself to switch over.

The consequence of not being part of Arcade dependency flow is that source-build has to treat this repo specially, with higher maintenance cost. When there are changes in this repo that are depended on by aspnetcore, the source-build team has to manually update the commit pointer used for source-build.

This turns into a product behavior risk, too. If the source-build team doesn't hear about a change in this repo (e.g. a bugfix to parse some unusual css), it will be missed and an out of date version of cssparser may ship in the source-built .NET SDK. I don't think any existing mechanism will detect the out of date package.

But, since there aren't plans to ever change the repo in any way, this may not ever happen. This is just a risk to weigh.

It sounds like if this repo got some PRs to add the standard Arcade infrastructure, they would be accepted? There's some provision for adding a basic Arcade implementation as part of source-build efforts.

> the WTE team

It was a little difficult to find this acronym, but it looks like "Web Tools Extensions", in some places AKA "Web Developer Tools". For future reference. 🙂

**Comment by SteveSandersonMS** [comment]
> It sounds like if this repo got some PRs to add the standard Arcade infrastructure, they would be accepted?

Yes, I would have no reason to object to that :)

It's just a matter of keeping this repo relatively simple and not doing a lot of extra work on it. Largely we plan to do as little as possible in this repo since the code is working fine and doesn't need any maintenance in the foreseeable future.

> it looks like "Web Tools Extensions"

Yes, exactly right. Sorry about using the acronym without definition!

**Comment by dagood** [comment]
Thanks! I think that wraps up this thread for now. 😄 

I have one more question I just filed, on the practical side: "What commit built Microsoft.Css.Parser 1.0.0-20200708.1? How can I tell in general?" #4
