### ISSUE TITLE
What commit built Microsoft.Css.Parser 1.0.0-20200708.1? How can I tell in general?

### ISSUE THREAD

**Issue by dagood** [dotnet/cssparser#4]
[In `v5.0.0-rc.2.20475.17`, dotnet/aspnetcore uses `1.0.0-20200708.1` of Microsoft.Css.Parser](https://github.com/dotnet/aspnetcore/blob/v5.0.0-rc.2.20475.17/eng/Versions.props#L193). Which commit built that version?

Usually I can find something in the nuspec, but I don't see anything:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Microsoft.Css.Parser</id>
    <version>1.0.0-20200708.1</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>https://github.com/dotnet/cssparser/blob/master/LICENSE.txt</licenseUrl>
    <description>CSS parser. Only intended for internal use within ASP.NET Core.</description>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <dependencies>
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
  </metadata>
</package>
```

I also don't see anything in the library's DLL in the assembly attributes, another common spot:

```
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(/*Could not decode attribute arguments.*/)]
[assembly: InternalsVisibleTo("Microsoft.Css.Parser.Test, PublicKey=0024000004800000940000000602000000240000525341310004000001000100f33a29044fa9d740c9b3213a93e57c84b472c84e0b8a0e1ae48e67a9f8f6de9d5f7f3d52ac23e48ac51801f1dc950abe901da34d2a9e3baadb141a17c77ef3c565dd5ee5054b91cf63bb3c6ab83f72ab3aafe93d0fc3c2348b764fafb0b1c0733de51459aeab46580384bf9d74c4e28164b7cde247f891ba07891c9d872ad2bb")]
[assembly: TargetFramework(".NETStandard,Version=v2.0", FrameworkDisplayName = "")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0-20200708.1")]
[assembly: AssemblyProduct("Microsoft.Css.Parser")]
[assembly: AssemblyTitle("Microsoft.Css.Parser")]
[assembly: AssemblyVersion("1.0.0.0")]
```

How can I trace back from the version of this package used by dotnet/aspnetcore to the specific commit of dotnet/cssparser that produced it?

Creating a dotnet/cssparser Git tag `v1.0.0-20200708.1` and continuing to do that that for future releases would work fine for me, but means manual work on the repo release end. This may be missed or done wrong depending on how much automation is set up for this repo.

I believe https://github.com/dotnet/sourcelink (used automatically by https://github.com/dotnet/arcade) is what normally makes the commit hash show up in the right places automatically in `dotnet` repos.

**Comment by SteveSandersonMS** [comment]
Looks like that build was from commit https://github.com/dotnet/cssparser/commit/d6d86bcd8c162b1ae22ef00955ff748d028dd0ee. I found this out by looking at the build history in https://dev.azure.com/dnceng/internal/_build?definitionId=878&_a=summary and then, for the version you specified, looking at the build log and seeing which Git commit was cloned.

As for getting the commit hash embedded in the package, I agree that would be a good thing. Most likely it would be possible by amending [the AzDO pipeline](https://github.com/dotnet/cssparser/blob/master/azure-pipelines.yml) even without a full migration to Arcade, though I don't immediately know precisely what steps to take.

**Comment by dagood** [comment]
Users who don't have Microsoft auth can't access https://dev.azure.com/dnceng/internal/_build?definitionId=878&_a=summary, so this isn't great, but it'll will work for source-build for now. Thanks for the build pointer.

(I suppose anyone else who needs to know for a new version of the package can just open a new issue on this repo to ask.)

The *general* instructions to use sourcelink without full Arcade onboarding are at https://github.com/dotnet/sourcelink#using-source-link-in-net-projects, but up to you if it seems worthwhile. I'm not sure though exactly what to fiddle with to make it put the commit hash where it needs to go without doing a bunch of other things.

And yeah, could also directly use [`$(Build.SourceVersion)`](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) as a property to `pack` to e.g. put it in the package description.

It's not critical for source-build, anyway.
